### ISSUE TITLE
how to get a new rate? like to a variable in $scope.

### ISSUE THREAD

**Issue by bleekbless** [sagarrabadiya/angular-rateyo#1]

**Comment by sagarrabadiya** [comment]
can u describe your scenario little bit so i can look into it

**Comment by bleekbless** [comment]
I have a view for users to rate others users profile.. there I have a rate-yo tag where the users can set the rate between 1 and 5 and then send that rate to the database... I want to set that value between 1 and 5 rate in  the $scope

**Comment by sagarrabadiya** [comment]
you can set it using ng-model in rateyo tag something like
https://github.com/sagarrabadiya/angular-rateyo/blob/master/example/index.html
if $scope.rating = 4 then start will be 4 loaded, you can check example in example/ directory
