### ISSUE TITLE
Prevent initial model.rating from triggering onSet

### ISSUE THREAD

**Issue by mokargas** [sagarrabadiya/angular-rateyo#2]
If I have the rateyo directive embedded in a template which is then injected in the page (just using a basic ng-if), my onSet handler will trigger with a value of 5, when $scope.rating = 5;

For my purposes,  I only want onSet to be called when the user actually clicks on the rating, not initially. Any ideas on how I can make this happen?

**Comment by sagarrabadiya** [comment]
you can set $scope.rating = null initially and in your set callback check if the rating is not null then only call your callback code to be executed something like below

```
$scope.rating = null;
$scope.set = function(event, data) {
     if(data.rating)
         alert('set event ' + data.rating);
};
```

**Comment by kgividen** [comment]
Thanks for this code.

I do have a similar request.  When I load the page I want to set $scope.rating to be whatever value was loaded from the database.  But if they change the value then I want it to call $scope.set and have it write to the database.

Currently, when settting $scope.rating after loading from the database it triggers the $scope.set function which then writes it back down to the database again.

Any ideas on how I can just update the stars without calling the .set function?

Thanks.

**Comment by sagarrabadiya** [comment]
you can compare the old rating value with new data.rating if they are not same then only send call to server for write in databse is that what you want?

**Comment by kgividen** [comment]
That's a good point.  I can probably do something like that.
