### ISSUE TITLE
How to change star size? Is it possible?

### ISSUE THREAD

**Issue by fabriciobs** [sagarrabadiya/angular-rateyo#4]
I tried to use 'starSvg' from this directive but not worked. I don't know how to do it.

**Comment by sagarrabadiya** [comment]
can you check which version of rateyo you are using? you can pass any option with option attribute
defined as here
https://github.com/sagarrabadiya/angular-rateyo/blob/master/example/index.html#L30

**Comment by fabriciobs** [comment]
Sorry about that. Works fine. Thanks.

**Comment by santoshcareerwaze** [comment]
@sagarrabadiya 
I'm using angular-rating-yo": "^1.0.0, and provided the options like below. 
$scope.readOnlyoptions = {
      starWidth: "14px",
      ratedFill: "#2196f3",
      normalFill: "#bcbcbc",
      readOnly: true,
      halfStar: false,
      fullStar: false,
      starSvg: "<svg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'><path d='M12 6.76l1.379 4.246h4.465l-3.612 2.625 1.379' '4.246-3.611-2.625-3.612 2.625' '1.379-4.246-3.612-2.625h4.465l1.38-4.246zm0-6.472l-2.833' '8.718h-9.167l7.416 5.389-2.833 8.718 7.417-5.388' '7.416 5.388-2.833-8.718' '7.417-5.389h-9.167l-2.833-8.718z'></path></svg>"
    };

still I'm getting the **Error: No such option as starSvg**

**Comment by fabriciobs** [comment]
Look at this documentation. Maybe help you: http://rateyo.fundoocode.ninja/#hack-starSvg
